# Site settings
title: DALI Sorrento 2025
subtitle: Data, Learning and Inference
permalink: "/:title.html"
description: > # this means to ignore newlines until "baseurl:"
  This is the website of the DALI Sorrento 2025 conference.
baseurl: "/sorrento2025" # the subpath of your site, e.g. /blog/

# If you want to create a twitter account for your conference include
# twitter name here
twitter_username: 

github_username:  dalimeeting

author:
  name: DALI
  # You might want to create an email for handling conference queries, e.g. dali2025@gmail.com. If you do, you can enter it here.
  email: 
comments: false

# Build settings
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
# change encoding for the generated output files to utf-8
encoding: utf-8
exclude: doc
remote_theme: dalimeeting/jekyll-theme
style: dali

ghub:
  edit: true
  repository: dali2025

# Also generate pages with dates in the future
future: true

# Place a banner image in assets/images and give its name here.
banner: sorrento.png 

conference:
  draft: true
  hide_tentative: false
  full_name: Data, Learning and Inference
  short_name: DALI
  name: Data, Learning and Inference
  # set to True if the programme is draft only.
  draft: true
  # set to True to hide tentative speakers
  hide_tentative: true 
  # Place an image of venue in assets/images and give its name here
  image: conference-venue.png
  proceedings:
    # When proceedings are published add url here.
    url:      
    show: false
  # Give details of the room in the venue here.  
  room:
  # Set the name of the venue (e.g. Caribe Hilton Hotel)  
  venue: Grand Hotel Vesuvio
  # Give the url of the venue here.
  venue_url: https://www.vesuviosorrento.com/
  # Give the conference location in the form City, Country here.
  location: Sorrento, Italy
  year: 2025
  # Give the instance of the conference here (e.g. 24th)
  instance: 7th
  # Styling for DALI is "Workshop on"  
  styling: Workshop on
  # Give the individual days that the conference will be held on here.
  dates:
  - 2025-04-13
  - 2025-04-14
  - 2025-04-15
  - 2025-04-16
  # Give the submission site details here.
  submission:
    # Whether to show the submission site.
    show: false
    # The URL of the submission site.
    url: 
    # The name of the submission site (e.g. Microsoft CMT Website)
    name: 
  deadlines:
    # Fill in the key dates as below.
    - name: Submission server open
      type: submission
      date: 
    - name: Paper submission deadline
      type: submission
      time: 2024-10-11
    - name: Author response period starts
      date: 
    - name: Author response period ends
      time:
    - name: Paper decision notifications
      date: 2024-10-18
      type: decision
    - name: Deadline for camera-ready papers
      time: 
    - name: Registration deadline
      date:
  # List program chairs here.
  chairs:
  - type: General Chairs
    people:
    - family: Lawrence
      given: Neil
      # Give their personal web page.  
      url: https://inverseprobability.com
      institute: University of Cambridge
    - family: Sondermann
      given: Hanni
      institute: University of Cambridge
    - family: Paleyes
      given: Andrei
      url: https://paleyes.info/
      institute: University of Cambridge
    - family: Cabrera-Jojoa
      given: Christian
      url: https://cabrerac.github.io/
      institute: University of Cambridge
  - type: Steering Committee
    people:
    - given: Zoubin
      family: Ghahramani
      url: "http://mlg.eng.cam.ac.uk/zoubin/"
      institute: University of Cambridge
    - given: Thomas
      family: Hofmann
      url: "http://www.da.inf.ethz.ch/people/ThomasHofmann/"
      institute: ETH Zurich
    - given: Neil D.
      family: Lawrence
      url: "http://inverseprobability.com"
      institute: University of Cambridge
    - given: Bernhard
      family: Schölkopf
      positon: Chair
      url: "http://ei.is.tuebingen.mpg.de/person/bs"
      institute: MPI Tübingen

